version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: fragrantly-inventive-gelding.data-1.use1.tembo.io
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a4VMimHciBDxg72p
      POSTGRES_DB: postgres

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a4VMimHciBDxg72p
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
